name: CI/CD for Next.js to S3

on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - 'develop'
      - 'staging'
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run CI checks (e.g., linting, tests)
        run: echo "run command test here"

  build:
    runs-on: ubuntu-latest
    if: github.ref_name == 'develop' || github.ref_name == 'staging' || github.ref_name == 'master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: echo "run command build here"

  deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == 'develop' || github.ref_name == 'staging' || github.ref_name == 'master'
    environment:
      name: ${{ github.ref_name }}
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to S3
        run: |
          aws s3 sync output s3://${{ vars.S3_BUCKET }}

      - name: Invalidate CloudFront Cache (Optional)
        run: |
#          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
