name: CI/CD for Next.js to S3

on:
  push:
#    branches:
#      - main # Change this to the branch you want to trigger the CI/CD

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # You can change this to your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run CI checks (e.g., linting, tests)
        run: echo "run command test here"

      - name: Build project
        run: echo "run command build here"

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get directory
        run: ls -R

      - name: Deploy to S3
        run: |
          echo ${{ vars.S3_BUCKET }}
          echo "$S3_BUCKET"
          echo "s3://$S3_BUCKET"
          aws s3 sync output s3://$S3_BUCKET

      - name: Invalidate CloudFront Cache (Optional)
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
